[package]
name = "crud"
version = "0.2.0"
edition = "2024"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tide = "0.16.0"
wasmi = "0.47.0"
